USE [master]
GO
/****** Object:  Database [CANVIA.EJERCICIOTECNICO.BD]    Script Date: 18/02/2022 20:50:36 ******/
CREATE DATABASE [CANVIA.EJERCICIOTECNICO.BD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CANVIA.EJERCICIOTECNICO.BD', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\CANVIA.EJERCICIOTECNICO.BD.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CANVIA.EJERCICIOTECNICO.BD_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\CANVIA.EJERCICIOTECNICO.BD_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [CANVIA.EJERCICIOTECNICO.BD] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CANVIA.EJERCICIOTECNICO.BD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [CANVIA.EJERCICIOTECNICO.BD] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CANVIA.EJERCICIOTECNICO.BD] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CANVIA.EJERCICIOTECNICO.BD] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CANVIA.EJERCICIOTECNICO.BD] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CANVIA.EJERCICIOTECNICO.BD] SET ARITHABORT OFF 
GO
ALTER DATABASE [CANVIA.EJERCICIOTECNICO.BD] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [CANVIA.EJERCICIOTECNICO.BD] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CANVIA.EJERCICIOTECNICO.BD] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CANVIA.EJERCICIOTECNICO.BD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CANVIA.EJERCICIOTECNICO.BD] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CANVIA.EJERCICIOTECNICO.BD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CANVIA.EJERCICIOTECNICO.BD] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CANVIA.EJERCICIOTECNICO.BD] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CANVIA.EJERCICIOTECNICO.BD] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CANVIA.EJERCICIOTECNICO.BD] SET  DISABLE_BROKER 
GO
ALTER DATABASE [CANVIA.EJERCICIOTECNICO.BD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CANVIA.EJERCICIOTECNICO.BD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CANVIA.EJERCICIOTECNICO.BD] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CANVIA.EJERCICIOTECNICO.BD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CANVIA.EJERCICIOTECNICO.BD] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CANVIA.EJERCICIOTECNICO.BD] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CANVIA.EJERCICIOTECNICO.BD] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [CANVIA.EJERCICIOTECNICO.BD] SET RECOVERY FULL 
GO
ALTER DATABASE [CANVIA.EJERCICIOTECNICO.BD] SET  MULTI_USER 
GO
ALTER DATABASE [CANVIA.EJERCICIOTECNICO.BD] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CANVIA.EJERCICIOTECNICO.BD] SET DB_CHAINING OFF 
GO
ALTER DATABASE [CANVIA.EJERCICIOTECNICO.BD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [CANVIA.EJERCICIOTECNICO.BD] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [CANVIA.EJERCICIOTECNICO.BD] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'CANVIA.EJERCICIOTECNICO.BD', N'ON'
GO
ALTER DATABASE [CANVIA.EJERCICIOTECNICO.BD] SET QUERY_STORE = OFF
GO
USE [CANVIA.EJERCICIOTECNICO.BD]
GO
/****** Object:  Table [dbo].[Product]    Script Date: 18/02/2022 20:50:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Product](
	[ProductId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[Brand] [varchar](50) NOT NULL,
	[CreateDate] [datetime] NOT NULL,
	[UpdateDate] [datetime] NULL,
	[Status] [varchar](3) NOT NULL,
	[Price] [decimal](18, 2) NOT NULL,
 CONSTRAINT [PK_Product] PRIMARY KEY CLUSTERED 
(
	[ProductId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Product] ON 
GO
INSERT [dbo].[Product] ([ProductId], [Name], [Brand], [CreateDate], [UpdateDate], [Status], [Price]) VALUES (1, N'Morochas', N'Nestle', CAST(N'2022-02-18T00:00:00.000' AS DateTime), CAST(N'2022-02-18T00:00:00.000' AS DateTime), N'ACT', CAST(0.80 AS Decimal(18, 2)))
GO
INSERT [dbo].[Product] ([ProductId], [Name], [Brand], [CreateDate], [UpdateDate], [Status], [Price]) VALUES (2, N'Inka Kola 1 Lt', N'Coca Cola', CAST(N'2022-02-18T00:00:00.000' AS DateTime), CAST(N'2022-02-18T00:00:00.000' AS DateTime), N'INA', CAST(10.00 AS Decimal(18, 2)))
GO
SET IDENTITY_INSERT [dbo].[Product] OFF
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Product_Estado]    Script Date: 18/02/2022 20:50:36 ******/
CREATE NONCLUSTERED INDEX [IX_Product_Estado] ON [dbo].[Product]
(
	[Status] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  StoredProcedure [dbo].[AddProduct]    Script Date: 18/02/2022 20:50:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
Create Procedure [dbo].[AddProduct] (@name varchar(50), @brand varchar(50), @createDate Datetime, @price decimal(18,2))
as
Insert into Product([Name], Brand, CreateDate, UpdateDate, [Status], Price)
values (@name, @brand, @createDate, @createDate, 'ACT', @price)
GO
/****** Object:  StoredProcedure [dbo].[DeleteProduct]    Script Date: 18/02/2022 20:50:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
Create Procedure [dbo].[DeleteProduct] (@productId int)
as
	Delete from Product
	Where ProductId =  @productId
GO
/****** Object:  StoredProcedure [dbo].[DeleteProductLogic]    Script Date: 18/02/2022 20:50:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
Create Procedure [dbo].[DeleteProductLogic] (@productId int)
as
	update Product
	set Status = 'INA'
	Where ProductId =  @productId
GO
/****** Object:  StoredProcedure [dbo].[GetProduct]    Script Date: 18/02/2022 20:50:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
Create Procedure [dbo].[GetProduct] (@id int)
as
select * from Product
where ProductId = @id
GO
/****** Object:  StoredProcedure [dbo].[ListProducts]    Script Date: 18/02/2022 20:50:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
Create Procedure [dbo].[ListProducts]
as
select * from Product
GO
/****** Object:  StoredProcedure [dbo].[UpdateProduct]    Script Date: 18/02/2022 20:50:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
Create Procedure [dbo].[UpdateProduct] (@productId int, @name varchar(50), @brand varchar(50), @updateDate Datetime, @price decimal(18,2))
as
update Product
set Name = @name, Brand = @brand, UpdateDate = @updateDate,  Price = @price 
Where ProductId =  @productId
GO
USE [master]
GO
ALTER DATABASE [CANVIA.EJERCICIOTECNICO.BD] SET  READ_WRITE 
GO
